### ISSUE TITLE
Game on Top

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#103]
Have a way to manually add a game to the top from an admin account?

**Comment by shreyansjain** [comment]
@anmolg this is what I am thinking:
create a new attribute `priority` and give an Int number. Default is 0, higher the number, higher the rank

**Comment by anmolg** [comment]
I do believe this is a future addition.

**Comment by EhJay22** [comment]
Yes, I believe that is a future addition
