### ISSUE TITLE
Games boxes

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#104]
All boarders thinned for all pages.
Circles removed around game type and number of participants. With the circles removed the while space between games should be very minimal now.

Within treat
when showing number of participants, remove the round boarder around it completed.

**Comment by shreyansjain** [comment]
![img_1248](https://user-images.githubusercontent.com/2359895/39091389-d184daca-45a7-11e8-83df-07e27f6e228c.PNG)
No border around participant count looks good, but, not so much for game_type label

**Comment by EhJay22** [comment]
Border looks better. 
The bottom symbol move it with the border. 
The top numbers pull so the border is the outer border then maybe give it a thin border? Whatever it is right now looks awkward

**Comment by shreyansjain** [comment]
![img_1251](https://user-images.githubusercontent.com/2359895/39091768-4b88c922-45b1-11e8-9fca-a1a5966fa01c.PNG)
Something like this?

**Comment by EhJay22** [comment]
![test](https://user-images.githubusercontent.com/37785631/39091901-dc8fbaaa-45b3-11e8-82af-889f4a8e08ad.PNG)

@shreyansjain similar to this?

**Comment by EhJay22** [comment]
then remove the white spacing between games since the circles  aren't in the way and we're on our way!

**Comment by shreyansjain** [comment]
Similar to what?

**Comment by EhJay22** [comment]
The top part of the picture. see how the circle fits into the corner instead out of outside it?

**Comment by EhJay22** [comment]
![test](https://user-images.githubusercontent.com/37785631/39091932-85fd51e2-45b4-11e8-976e-b156020282cd.PNG)

**Comment by shreyansjain** [comment]
![img_1253](https://user-images.githubusercontent.com/2359895/39091939-ae7380ba-45b4-11e8-8330-051870c809b8.PNG)
Not sure why you see top right differently
