### ISSUE TITLE
Side Menu Font

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#107]
The pop up menu with "My Games, My Treats, and Settings" 

Change the font to San Francisco.

**Comment by EhJay22** [comment]
That looks good for the font. Dunno about the glow. Any chance we can maybe lose that and leave it regular or bold?

**Comment by shreyansjain** [comment]
![img_1246](https://user-images.githubusercontent.com/2359895/39091139-f29e1d34-45a2-11e8-9451-e744922967b9.PNG)
Looks good now?

**Comment by EhJay22** [comment]
Yeah, looks good
