### ISSUE TITLE
Game type colour test

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#113]
For the game types showing up (their symbol on the game pages)

Lightening bolt / flash hex colour: #00857A
Star hex colour: #F9B200
Friends hex colour: can the mddle friend be #00857A and the two people on the outsides be #F9B200

**Comment by shreyansjain** [comment]
You have to re-login in order to see the changes. 

And I wasn't able to change the icon for Friends with different hex's. Can you ask Alex to do it?

**Comment by EhJay22** [comment]
@shreyansjain I let Roberto know. Other than that, looks good so I'll close this issue for now.

**Comment by shreyansjain** [comment]
@EhJay22 try now? Make sure to signout and login again to see the new colors
