### ISSUE TITLE
Clicking on a game page

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#122]
So when on the main page you click a game..that page!

Tweak a few things:

- Bold the name of the company
- Spacing above the game and below the No / # of participants / Yes is too large.
Make the game similar in size to the My Treats page by:
- Spacing of the photo needs to be closer to the edges of the boarder
- Same size for fonts as the My Treats page

Essentially keeping all the pages looking consistent.

**Comment by shreyansjain** [comment]
![img_1266](https://user-images.githubusercontent.com/2359895/39460453-4d194a10-4cb8-11e8-8564-bf463997945b.PNG)
![Uploading IMG_1267.PNG…]()

This is the best I could do
