### ISSUE TITLE
Dev Page

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#124]
Some of this is from the meeting at Blenz and some of it is additional:

When creating a game can we remove the option to add in the name of a business again. The business has been added on the other page and it should automatically just be there. Either have it pre-filled or get rid of the option completely.

With that done, the game type will be the first option now.

**Flash Games:**
Wording needs to change as it's doing something different.
Current: "What Item you are giving away"
Change to: "What item are you discounting (no alcohol)?"

Current: "Describe the winning prize in more detail"
Change to: "Describe what you are discounting in more detail"

Remove the Number of participants option.

Remove the runner up discount option

Current: "Date Time"
Change to" What time would you like your flash sale to start?"

Add a box:

"What time would you like your flash sale to end?"
with options of: 1 hour, 2 hours, 3 hours, 4 hours.

**For Regular and Friends Game**

Current: "What free item are you giving away"
Change to: "What free item are you giving away (No alcohol)"

Current: "Date Time"
Change to "What time would you like your game to start?"

Runner up discount
Change to options to 15, 20, 25, 30, and 40 % 

**Friends Game**

Current: "What free item are you giving away?"
Change to "What free item(s) are you giving away to the entire group?"

Maximum group size
Make it options with 10, 15, 25, 30 groups

Number of participant in groups
Change options to 1, 2, 3 friends

Current: "Runner Up Discount"
Change to: Runner up discount for entire group

**Packages**
This option should only show up on an admin account (ie: Roberto's) as he should be the only one making them, not regular companies.

**Comment by anmolg** [comment]
Current: "Date Time"
Change to" What time would you like your flash sale to start?"

Currently no start time concept exists. Will investigate how much effort it is. 

Add a box:

"What time would you like your flash sale to end?"
with options of: 1 hour, 2 hours, 3 hours, 4 hours.

Agreed that a default time will be used across all flash games

Current: "Date Time"
Change to "What time would you like your game to start?

It is for finish time

Hiding fields based on game selection, will investigate and let you know.

**Comment by shreyansjain** [comment]
> When creating a game can we remove the option to add in the name of a business again. The business has been added on the other page and it should automatically just be there. Either have it pre-filled or get rid of the option completely.
Need to resolve #106

**Comment by anmolg** [comment]
Runner up discount has been updated in technical documentation
