### ISSUE TITLE
Spacing

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#127]
On main page there's a tonne of white spacing at the top. Please reduce it.

Also after clicking a game for more info / join there's too much white spacing at the top. Please reduce

**Comment by shreyansjain** [comment]
![img_1337](https://user-images.githubusercontent.com/2359895/41077913-653660e6-69ce-11e8-959d-da3bae281e19.PNG)
Reduced the space on the main page. The space cannot be reduced on the game info page
