### ISSUE TITLE
Getting kicked off

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#129]
We created a package game. When clicking on it to join, it's kicking us off of the app. Tried on multiple phones and it is kicking out of the game.

**Comment by anmolg** [comment]
Package game will not work through the UI. You need to create two regular games, then I will give you a link to click on which will merge the two games together.

**Comment by EhJay22** [comment]
It was working before. 
I don't see how we'll make it work as two separate games as they'd both say different things and this is making things more complicated.

**Comment by anmolg** [comment]
Package games was never working through the UI. If it was, it was unintended. A package game is by definition more than 1 game, so we will need to create two separate games for that, then a later process causes it to be merged.

**Comment by anmolg** [comment]
Do you use Lastpass? How should I share database username and password?

**Comment by EhJay22** [comment]
Sent you an email
