### ISSUE TITLE
Page Refresh - Bug

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#140]
When on the main page there's the options: All, Flash, Package, Friends
If you pull down to refresh the page it shows the "All" page instead of the current page that you are on.

**Comment by shreyansjain** [comment]
This is by design not by bug

**Comment by EhJay22** [comment]
On main page.
Click flash.
Pull down to refresh.
Still on flash page and see flash games.

Same with any type of game. It is disorienting to users if it switches to
All but shows as being on flash
