### ISSUE TITLE
Number of Participants is off

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#141]
When selecting "2" participants in the dev-vendor page, it says that it's two.
But once you go into the game it's showing up as 15 participants being required.

**Comment by shreyansjain** [comment]
Which game is this?

**Comment by anmolg** [comment]
I see participants as 2, 5, or 10.

Can you please take a screenshot?

**Comment by EhJay22** [comment]
This is what i see. And it's the same on an iPad too.

![img_0004](https://user-images.githubusercontent.com/37785631/41487195-7dc1480e-709c-11e8-9f72-d3ec7f64d6e1.jpg)

**Comment by shreyansjain** [comment]
Changing the values in the database on the fly causes this issue. Try signing out and login again to check if you see the right numbers

**Comment by EhJay22** [comment]
Fixed
