### ISSUE TITLE
Full Games still on list

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#142]
There's a bunch of games that have the full number of participants but they are still showing on the list of games.

**Comment by shreyansjain** [comment]
What game and username you are seeing this error with?

**Comment by EhJay22** [comment]
Ryde Today
Our Treat
Our Treat
Our Treat
Our Treat
Our Treat
Our Treat
Our Treat

**Comment by anmolg** [comment]
I don't see any game with title or winner discount as our Treat or Ryde Today.

The closest one I see is Limo Ryde. Limo Ryde has 2 participants, For that game I see a username created by Shreyans for that.

Please elaborate further.

**Comment by EhJay22** [comment]
![img_0005](https://user-images.githubusercontent.com/37785631/41487187-7401025a-709c-11e8-8826-8563344c5420.jpg)
Here's a screenshot of what i see.

**Comment by shreyansjain** [comment]
Same as #141. Try to re-login to the app and see if it works.

**Comment by EhJay22** [comment]
Logged out, but game is crashing now when I scroll through.

**Comment by shreyansjain** [comment]
Will tell you when to start testing, still debuggin few things

**Comment by EhJay22** [comment]
okay

**Comment by EhJay22** [comment]
Still showing up. "Our Treat" Free Freinds game. 2/2

**Comment by anmolg** [comment]
Can you please indicate username, and approx date/time of day you saw this game?
