### ISSUE TITLE
Join this Game prompt

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#146]
Where it says "I have read, understand and accept the Terms and conditions.. Make the terms and conditions word be a link to the our Terms of Service page.

**Comment by shreyansjain** [comment]
I think, we discussed why we should not do this and the alternate was to add the Terms and Conditions section in the Settings page

**Comment by EhJay22** [comment]
After consulting with a lawyer who specializes in corporate law, she said that not doing so could result in us being held liable for each game. So let's just link it. Thanks.

**Comment by shreyansjain** [comment]
With the current implementation of showing the Join this game view, this will not be possible. The entire UI view will change if we need to add the text that will point to a url. 
cannot guarantee this can be done until sunday

**Comment by EhJay22** [comment]
Yeah, we can wait until Sunday for that.

**Comment by shreyansjain** [comment]
Seems quite a bit of extra work, unfortunately, have to approved as a change. Can you approve it?

**Comment by shreyansjain** [comment]
@EhJay22 @ourtreat can you guys approve this as a change?

**Comment by EhJay22** [comment]
Why is that a change? It's something that's required for legal reasons.

**Comment by shreyansjain** [comment]
We already agreed to the current flow previously (no links in the prompt) and the links requirement came just recently. Hence, a change

**Comment by shreyansjain** [comment]
And any update on this?

**Comment by EhJay22** [comment]
The issue being on the Mock Up from page 20, it indicated having a prompt with a scrollable terms and conditions there. If doing it the same as the mock up is quicker, that would be acceptable otherwise, please go with the mock up. For each game type.

**Comment by shreyansjain** [comment]
It could be a prompt and a link to T&C in the prompt. The view will be different. 
However, either cases will be considered a change. Can you approve the change# 7?

**Comment by EhJay22** [comment]
How is it a change if it is actually like that in the mock up?

**Comment by shreyansjain** [comment]
We discussed in one of the meetings at Waves and Roberto agreed to make it look like this. I don't have the meeting minutes for all the meetings, but, this has been like this for quite a bit of time and since the issue of changing the UI was brought up after the beta testing, hence, it will be considered a change. 
Side note, the UI change is quite a bit of work. It'll look very different to what you see now

**Comment by EhJay22** [comment]
Without anything to say that this was said and agreed upon by all parties, that doesn't work. It needs to be in there and it is not a change.

**Comment by shreyansjain** [comment]
I am sorry, but, this would be a change.

**Comment by EhJay22** [comment]
Not sure if you want to do it out of this or close this one and make a new Issue but:

When creating an account have the ToS and a box that the user must manually click stating that they have read and agree to the ToS.

On the vendor page, when creating a new business account, have the ToS and a box that the user must manually click stating that they have read and agree to the ToS.

Approved Change #9

**Comment by shreyansjain** [comment]
![img_1759](https://user-images.githubusercontent.com/2359895/42856359-c332db7a-89f9-11e8-9f3d-5da2da8c40e6.PNG)

Does this look good ?

**Comment by shreyansjain** [comment]
![img_1760](https://user-images.githubusercontent.com/2359895/42856495-5ef37592-89fa-11e8-9170-f41c95318e58.PNG)
And if not selected, show this error

**Comment by EhJay22** [comment]
Looks good.
Only question is: if the click the Tos hyperlink, is there an easy way for them to get back? And will anything that they've already filled out be there or not?

**Comment by shreyansjain** [comment]
Yep, the user can click the back button from the top. And no, the already filled out information will retain.

**Comment by EhJay22** [comment]
Perfect. That'll work. 
Thanks

**Comment by EhJay22** [comment]
Perfect!
