### ISSUE TITLE
Side Bar

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#147]
**Currently**
My Games
My Treats
Settings
**add:** Add Friends

The background is currently transparent. Make it solid white.

**Comment by anmolg** [comment]
Strictly speaking, this will be considered a change. Please verify this is a change and we will make it as part of the 10 changes permitted.

**Comment by EhJay22** [comment]
I don't recall any consultation going on for the side bar, otherwise this would have been suggested a long time ago. Is there anything showing where this was talked about and decided upon (email or otherwise?)

**Comment by EhJay22** [comment]
Last month we had decided (at your request) on leaving out the minor changes while the bulk of the big changes were made. Now that the big things are out of the way and we have been in consultation with users, this is a change that nearly every person playing with the app has asked for.

**Comment by anmolg** [comment]
Please identify all changes deemed "minor".

**Comment by EhJay22** [comment]
Yes, friends thing will be a change.

**Comment by shreyansjain** [comment]
![img_1719](https://user-images.githubusercontent.com/2359895/42304839-175afab0-7fdd-11e8-9cc2-32236aa32c48.PNG)
This is the most I could do, looks good?

**Comment by EhJay22** [comment]
Yeah, that looks good. Still waiting on the friends thing though.

**Comment by EhJay22** [comment]
Can we switch it from "Add Friends" to "+ Friends" ?

**Comment by shreyansjain** [comment]
sure

**Comment by EhJay22** [comment]
Thanks

**Comment by EhJay22** [comment]
Looks good!
