### ISSUE TITLE
Friends icon

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#149]
When looking at your friends it looks like it's just a stock image. Should be showing up as the picture the person uploads or their facebook profile photo

**Comment by shreyansjain** [comment]
![img_1706](https://user-images.githubusercontent.com/2359895/42137990-e18e9ad6-7d2a-11e8-82fe-2c902743f088.PNG)

For users who do not have any image associated to their account, we show the stock user image, otherwise, we show the user's image (see above image)
