### ISSUE TITLE
Sign up

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#155]
When going to sign up for an account, there is no option on the "Sign up" page to make an account using facebook.
Currently it's showing up under the "Sign In" page. There should be an option on the "Sign up" page to sign up using facebook.

**Comment by anmolg** [comment]
Because you never actually signup with Facebook. You only signin with Facebook

**Comment by EhJay22** [comment]
Maybe this is something technical that I don't understand, but how do you sign in with something if you haven't signed up with it?

**Comment by anmolg** [comment]
This is not actually smoething technical, it's just a weird part of Facebook. Since you are logging in with Facebook, the idea is, everyone has an account on OurTreat, which is why we have Facebook login in the first place. That is my understanding at least, @shreyansjain might have some more input

**Comment by EhJay22** [comment]
Mmm I see. Can the code be copy and pasted then from the sign in page to the sign up page?

**Comment by shreyansjain** [comment]
As per our phone conversation, making it as a change.
