### ISSUE TITLE
Import Phone Contacts

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#159]
When trying to import friends this error  pops up

![internal server error](https://user-images.githubusercontent.com/37785631/42254835-8ebac90e-7efd-11e8-8e32-1a4ceed8c2b9.jpg)

**Comment by anmolg** [comment]
Please try again.

**Comment by EhJay22** [comment]
I just logged out, closed the app, and logged back in and it still isn't working for me. Still getting Error, Internal server error.
Roberto had the same issue as well.

**Comment by anmolg** [comment]
Sorry - I deployed to development environment, rather than prod. Redeploying now.

**Comment by anmolg** [comment]
Just confirmed prod deployment - can you try agian

**Comment by EhJay22** [comment]
I'm logged in with Facebook currently, and there's no error message showing up, but when I click "Import Phone Contacts" it spins then nothing happens. I have at least 5 users saved in my phone as a contact. 
Same thing is happening when I try to click "Import Facebook Contacts"

**Comment by shreyansjain** [comment]
Can you list the people from your contact list that you are expecting them to see here? Their phone numbers are important. 
We'll then check on our production database if those people used that phone number when signing up.

**Comment by EhJay22** [comment]
Brian - 778-322-7404
Larissa 604-356-0622 
Paul - 778-680-1676
Roberto - 604-961-4212
Samantha - 604-202-8332

**Comment by shreyansjain** [comment]
@anmolg can you see if these users exist in prod db?

**Comment by anmolg** [comment]
![image](https://user-images.githubusercontent.com/2329166/42432419-4d807d02-82ff-11e8-86fc-85a5554e82ca.png)

Don't see any of these numbers.

**Comment by EhJay22** [comment]
Good to know. It appears  people  aren't using their correct number. I'll close this issue then.
