### ISSUE TITLE
Sign Up

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#161]
A new user was trying to sign up and got this bug showing
Date: 2018-07-03
Time: 19:00

![sign up bug](https://user-images.githubusercontent.com/37785631/42254892-da57ffd0-7efd-11e8-974d-f85e14397aa6.jpg)

**Comment by shreyansjain** [comment]
PS: All existing users will not work in dev or production once the new build is released

**Comment by EhJay22** [comment]
It's stuck on this page, can't even get to the reset password page anymore.

![password](https://user-images.githubusercontent.com/37785631/42413268-de31643a-81d1-11e8-9b6b-3726aa1cb0a3.jpg)
