### ISSUE TITLE
My Treat - Prize

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#162]
After winning a discount of a second prize for a  company, it revered the new prizes time of instead showing up as 48 hours and counting to the same time as the prize from a day earlier. There's two pictures to kinda show it. We played two games 5 minutes apart (top one from each game) and the other two were  from a previous time played.
Date: 2018-07-03
Time: 19:33
![36554852_10210265735553213_3958391767237132288_n](https://user-images.githubusercontent.com/37785631/42254945-228ce87e-7efe-11e8-86d9-ed7e6934b216.jpg)

![prize](https://user-images.githubusercontent.com/37785631/42255017-7638bcdc-7efe-11e8-831d-a6fcd173fcfc.jpg)

**Comment by shreyansjain** [comment]
Can you test this again?

**Comment by EhJay22** [comment]
Looks like it's fixed now. Thanks
