### ISSUE TITLE
Account Registration

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#173]
When creating an account, user was unable to make their age correctly.
August to November wouldn't work
Day 5+ would not work. It would scroll right past them.

Iphone: 6
Date: 2018-07-04
Time: 20:00

![bug](https://user-images.githubusercontent.com/37785631/42301849-66ca2b4a-7fcc-11e8-98ac-80f0e41fdc80.jpg)

**Comment by shreyansjain** [comment]
Its not a bug, rather, reason you cannot go after August because the year is set to 2018. You need to change the year first, since you cannot set a birthdate in the future

**Comment by EhJay22** [comment]
Okay, good to know.
