### ISSUE TITLE
My Games / Friends Game

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#177]
The look of Friends games should be the same format as regular / flash games in the My Games and My Treats pages.

![friends game](https://user-images.githubusercontent.com/37785631/42421435-80c3a146-828a-11e8-82cb-45c4c68ae125.jpg)

**Comment by shreyansjain** [comment]
This is part of the mockups and Roberto specifically asked to show status of the friends joining.

**Comment by EhJay22** [comment]
Yes, but the picture and title still need to be the same as the other games.

**Comment by shreyansjain** [comment]
![42421435-80c3a146-828a-11e8-82cb-45c4c68ae125](https://user-images.githubusercontent.com/2359895/42422404-1a9449ce-829a-11e8-83b9-43dc010d961f.png)

I have just edited it myself (not built it since it will be quite a bit of work)

**Comment by EhJay22** [comment]
Yeah, that looks good. It'll look the same or similar on My Treats as well? And are packages looking the same? We haven't been able to test it as I don't have access on the database server yet.  Anmol said he was working on it.

**Comment by shreyansjain** [comment]
That will be a change. I think, on My Treats, it looks like other games. 
Regarding package game, it looks like other games in My Games and My Treats

**Comment by EhJay22** [comment]
Yes, approved as change #5 

Please also make sure that the prompts that users see when someone is trying to add them look like this from the mock ups. 

![mock up](https://user-images.githubusercontent.com/37785631/42426793-85ae4ad0-82df-11e8-8999-95f53255d886.jpg)
![mock u p 2](https://user-images.githubusercontent.com/37785631/42426794-85c7ef1c-82df-11e8-901c-8593141471b1.jpg)

**Comment by shreyansjain** [comment]
Just fyi, this is change # 6

**Comment by EhJay22** [comment]
Can you link the other 5 on GitHub, please? I must be missing one.

**Comment by shreyansjain** [comment]
https://github.com/OurTreatApp/OurTreat-iOS/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Achange-approved+

**Comment by shreyansjain** [comment]
Still approving it?

**Comment by EhJay22** [comment]
Yes, it's approved as #6

**Comment by shreyansjain** [comment]
![img_1727](https://user-images.githubusercontent.com/2359895/42489458-feef4ba2-83bf-11e8-8781-694bab586dbb.PNG)
Does the above screenshot looks good?

**Comment by EhJay22** [comment]
Yup, looks good

**Comment by shreyansjain** [comment]
This has been added in the last release. Can you test it out and if works, close the issue please
