### ISSUE TITLE
Flash Games - wording

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#180]
I created a game (Pizza House, today @ 17:30) win the wording "2 for 1 pizza" ... It prefills the beginning with "You could  win ____________". This is misleading as  for flash games they aren't actually winning anything. Please change it to "Flash Sale - _______________".

Thanks

**Comment by shreyansjain** [comment]
So, for flash sale, you want to say:
"Flash Sale - You could win ____________"?

**Comment by EhJay22** [comment]
No, say "Flash Sale - ___________________"
So if the user inputs 2 for 1 pizzas it would say "Flash Sale - 2 for 1 pizzas"
