### ISSUE TITLE
Opening My games push notification to open My games page

### ISSUE THREAD

**Issue by shreyansjain** [OurTreatApp/OurTreat-iOS#181]

**Comment by shreyansjain** [comment]
@anmolg looking for `notification_type = 1 (number)` in the body

**Comment by anmolg** [comment]
Yup - id 1 is being sent

**Comment by EhJay22** [comment]
With the app completely closed, I clicked on the notification and it only takes me to the main page.

**Comment by shreyansjain** [comment]
It will open My Games page depending on the type of push notification received. @anmolg will tell you which notifications will do that.

**Comment by EhJay22** [comment]
Well, the notification of a game being filled stating 1 minute countdown in My games. After go to My Treats... that one is supposed to open on the My Games page when you click on it, but it isn't. So, it's  not working properly.

**Comment by shreyansjain** [comment]
@anmolg can you make sure if the above notification had the attribute?

**Comment by EhJay22** [comment]
Well, it worked now with the current version, so I'll just close this.
