### ISSUE TITLE
Countdown Flow (Applies to all except Flash game)

### ISSUE THREAD

**Issue by anmolg** [OurTreatApp/OurTreat-iOS#78]
1. Game clicked, full participants
--- push notification
2. Go to my games, countdown is visible
3. Once countdown finishes, show go to my treats
4. View treat. Winner or runner up.

**Comment by shreyansjain** [comment]
![img_1233](https://user-images.githubusercontent.com/2359895/38656037-d73f13a0-3dcc-11e8-97ea-84e8cb0bb4f2.PNG)
@EhJay22 thoughts on the 60 seconds timer?

**Comment by EhJay22** [comment]
It's a start.

Can you:
Remove the hours and minutes. 
Add in milliseconds. 
Add the word "seconds" after the clock showing
Make it larger, covering up almost the whole square
Change the font to look similar to the one mock up on page 18, I believe it is Cookie-Regular (Regular)
And font colour: to match the present in the logo, which I believe shows up on the vendor login page in the word "vendor" which may be Hex #f8b600
