### ISSUE TITLE
Show Contact List option when sending an invite for the app via text 

### ISSUE THREAD

**Issue by anmolg** [OurTreatApp/OurTreat-iOS#85]
5 hrs additional effort. 

Accepted.

**Comment by shreyansjain** [comment]
Reviewing this now and it seems like it'll take more than 2.75 hours to implement this feature. How would you like to proceed?

**Comment by EhJay22** [comment]
It's approved as change #8

**Comment by shreyansjain** [comment]
Correct and as per the contract, a change is only for 2.75 hours and from my investigation, it could more than 2.75 hours

**Comment by shreyansjain** [comment]
Let me think about it if it can be done in a different way

**Comment by shreyansjain** [comment]
What would you like the message body to be? 
"Hey, checkout OurTreat.ca to earn free rewards"

**Comment by shreyansjain** [comment]
![img_1761](https://user-images.githubusercontent.com/2359895/42859616-ecf18272-8a08-11e8-85e7-caffafd33a3e.PNG)
![img_1762](https://user-images.githubusercontent.com/2359895/42859615-ecc642f6-8a08-11e8-936f-0f3f042e9af5.PNG)
![img_1763](https://user-images.githubusercontent.com/2359895/42859614-ecac8e4c-8a08-11e8-85cc-388a41b42a62.PNG)

Does the above flow make sense? 
Also, please let me know the text that you'd like to send to the invitees now.

**Comment by EhJay22** [comment]
Flow makes sense and is good.
As for the text I'll get back shortly.

**Comment by EhJay22** [comment]
Looks good
