### ISSUE TITLE
Spacing / Font

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#88]
- Change font for the app to San Francisco for iOS
- Reduce white space between games on main pages
- Reduce white space between games and edge of screen
- Center the name of the company between the edge and the round circle at the top and increase font size
- In the games pages center the name of the company at the top of the game and make font size bigger

**Comment by shreyansjain** [comment]
![img_1231](https://user-images.githubusercontent.com/2359895/38596506-c6c219bc-3d06-11e8-8025-263b03c11571.PNG)
@EhJay22 does this look good? 
Cannot reduce the whitespace in the bottom

**Comment by EhJay22** [comment]
Looks good. Any chance the white space on the side can be reduced? If not, keep it as is.
