### ISSUE TITLE
My Treat

### ISSUE THREAD

**Issue by EhJay22** [OurTreatApp/OurTreat-iOS#92]
Have box size of Treat roughly the same size as the main game pages boxes.

**Comment by shreyansjain** [comment]
![img_1230](https://user-images.githubusercontent.com/2359895/38595752-3f8b8658-3d02-11e8-993c-1ab85af36f25.PNG)
@EhJay22 does this look good?

**Comment by EhJay22** [comment]
Size of the box is perfect. Anyway to make the picture be bigger and the text now uniform / evenly spaced in the box?

**Comment by shreyansjain** [comment]
If we make the picture bigger (its a square), then, the following text would be really tiny. 

What do you mean by
>the text now uniform / evenly spaced in the box?

**Comment by EhJay22** [comment]
There's too much white space now on the prize.

If the picture were roughly 25% larger and the text centered could that work?

**Comment by shreyansjain** [comment]
Let me think about it. Just a thought, how about it, looks similar to the main page?
full sized image and under it, the company name and then, the prize details and the treat button?

**Comment by EhJay22** [comment]
That would make sense. It would keep everything consistent that way.

**Comment by shreyansjain** [comment]
![img_1232](https://user-images.githubusercontent.com/2359895/38655127-b578fd12-3dc7-11e8-835c-8b6d126d7bf1.PNG)

@EhJay22 does the UI look good?
